interface Invoice {
  "invoiceNumber": string,
  "sbrReferenceId": string,
  "agreementId": string,
  "anchorId": string,
  "counterPartyId": string,
  "documentType": string,
  "documentNumber": string,
  "currency": string,
  "amount": number,
  "date": string,
  "valueDate": string,
  "dueDate": string,
  "agreedPaymentDate": string,
  "portOfLoading": string,
  "portOfDischarge": string,
  "shipmentCorporation": string,
  "realBeneficiary": string,
  "financingRate": number,
  "financingInterestAmount": number,
  "rebateAmount": number,
  "netFinancingInterestAmount": number,
  "financeValueDate": string,
  "financeDueDate": string,
  "financeId": string,
  "financingAmount": number,
  "financingBalance": number,
  "paidBy": string,
  "paymentDate": string,
  "paymentAmount": number,
  "principalPaid": number,
  "interestPaid": number,
  //"status": string
}
const inits: Invoice = {
  "invoiceNumber": "",
  "sbrReferenceId": "",
  "agreementId": "",
  "anchorId": "",
  "counterPartyId": "",
  "documentType": "",
  "documentNumber": "",
  "currency": "",
  "amount": 0.00,
  "date": "",
  "valueDate": "",
  "dueDate": "",
  "agreedPaymentDate": "",
  "portOfLoading": "",
  "portOfDischarge": "",
  "shipmentCorporation": "",
  "realBeneficiary": "",
  "financingRate": 0.00,
  "financingInterestAmount": 0.00,
  "rebateAmount": 0.00,
  "netFinancingInterestAmount": 0.00,
  "financeValueDate": "",
  "financeDueDate": "",
  "financeId": "",
  "financingAmount": 0.00,
  "financingBalance": 0.00,
  "paidBy": "",
  "paymentDate": "",
  "paymentAmount": 0.00,
  "principalPaid": 0.00,
  "interestPaid": 0.00,
 // "status": ""
}

export { Invoice, inits };
