import {financing} from "./financing";
import {Invoice} from "./invoice";

interface Payment {
  "paymentId": string,
  "sbrReferenceId": string,
  "agreementId": string,
  "buyerId": string,
  "sellerId": string,
  "buyerName": string,
  "sellerName": string,
  "paymentType": string,
  "businessType": string,
  "transactionDate": Date,
  "finance": [financing]
  "valueDate": Date,
  "paymentCurrency": string,
  "paymentAmount": number,
  "financeCurrency": string,
  "financeTotalDue": number,
  "paymentTotalDue": number,
  "interestRefunded": number,
  "cableChargeCurrency": string,
  "cableChargeAmount": number,
  "communicationChargeCurrency": string,
  "communicationChargeAmount": number,
  "paymentNotes": string,
  "refundInterestDetails": string,
  "debitAccount": string,
  "creditAccount": string,
  "diaryId": string,
  "diaryDueDate": string,
  "diaryNarrative": string,
}
const inits: Payment = {
  "paymentId": "",
  "sbrReferenceId": "",
  "agreementId": "",
  "buyerId": "",
  "sellerId": "",
  "buyerName": "",
  "sellerName":"",
  "paymentType": "",
  "businessType": "",
  "transactionDate": new Date(),
  "finance": [{} as financing],
  "valueDate": new Date(),
  "paymentCurrency": "",
  "paymentAmount": 0.00,
  "financeCurrency": "",
  "financeTotalDue": 0.00,
  "paymentTotalDue": 0.00,
  "interestRefunded": 0.00,
  "cableChargeCurrency": "",
  "cableChargeAmount": 0.00,
  "communicationChargeCurrency": "",
  "communicationChargeAmount": 0.00,
  "paymentNotes": "",
  "refundInterestDetails": "",
  "debitAccount": "",
  "creditAccount": "",
  "diaryId": "",
  "diaryDueDate": "",
  "diaryNarrative": "",
}

export { Payment, inits };
