import { Agreement } from "./agreement";
import { Customer } from "./customer";
import { rm } from "./OAAdmin/Request/rm";

export class Sbrreq {
  "sbrId": string;
  "directContactFlag": string;
  "expiryDate":string;
  "recourseFlag": string;
  "appliedLimitCurrency": string;
  "limitTypeFlag": string;
  "transactionDate": string;
  "natureOfBusiness": string;
  "goodsDescription": string;
  "appliedLimitAmount": number;
  "anchorPartyAccountId": string;
  "counterPartyAccountId": string;
  "paymentTermsDays":number;
  "paymentTermsCondition": string;
  "commercialContractDetails": string;
  "autoFinanceAvailability": string;
  "autoFinancing": boolean;
  "autoSettlement": boolean;
  "anchorCustomerContactName": string;
  "realBeneficiary": string;
  "anchorCustomerAddressLine1": string;
  "anchorCustomerAddressLine2": string;
  "anchorCustomerAddressLine3": string;
  "anchorCustomerPOBox": string;
  "anchorCustomerEmail": string;
  "anchorCustomerFax": string;
  "anchorCustomerTelephone": string;
  "counterPartyContactName": string;
  "counterPartyAddressLine1": string;
  "counterPartyAddressLine2": string;
  "counterPartyAddressLine3": string;
  "counterPartyPOBox": string;
  "counterPartyEmail": string;
  "counterPartyFax": string;
  "counterPartyTelephone": string;
  "managementFeeCurrency": string;
  "managementFeeAmount": number;
  "administrativeFeeCurrency": string;
  "administrativeFeeAmount": number;
  "earlyPaymentFeeCurrency": string;
  "earlyPaymentAmount": number;
  "factoringCommissionRate": number;
  "financingProfitMarginRate": number;
  "rebateRate": number;
  "rebateAccount": string;
  "financingInformation": string;
  "invoiceServiceChargeCurrency": string;
  "invoiceServiceChargeAmount": number;
  "maxLoanPercentage": number;
  "profitRateType": string;
  "documentsRequired": string;
  "limitReference": string;
  "earMarkReference": string;
  "limitExpiry": string;
  "limitCurrency": string;
  "limitAmount": string;
  "cashMargin": number;
  "agreement":[Agreement];
  "anchorCustomer":[Customer];
  "counterParty":[Customer];
  "rm":[rm];
}
