export class cInvoice {
  "invoiceNumber": string;
  "sbrReferenceId": string;
  "agreementId": string;
  "anchorId": string;
  "counterPartyId": string;
  "documentType": string;
  "documentNumber": string;
  "currency": string;
  "amount": number;
  "date": string;
  "valueDate": string;
  "dueDate": string;
  "agreedPaymentDate": string;
  "portOfLoading": string;
  "portOfDischarge": string;
  "shipmentCorporation": string;
  "realBeneficiary": string;
  "financingRate": number;
  "financingInterestAmount": number;
  "rebateAmount": number;
  "netFinancingInterestAmount": number;
  "financeValueDate": string;
  "financeDueDate": string;
  "financeId": string;
  "financingAmount": number;
  "financingBalance": number;
  "paidBy": string;
  "paymentDate": string;
  "paymentAmount": number;
  "principalPaid": number;
  "interestPaid": number;
  //"status": string
}
